name: Build/release

on: [ push, workflow_dispatch ]

jobs:
  #mac-release:
  #  runs-on: macos-latest

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Build Linux
        run: |
          docker build . -t builder
          docker run -v $PWD:/build:z builder bash -c "cd /build && make ci"
      - name: Create a release  
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ inputs.release_version }}"
          description: "${{ inputs.release_changelog }}"
          prerelease: false
          files: |
            build/*.AppImage
            build/*.exe
            build/*.dmg