name: Build/release

on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build/release Electron app
        uses: asivery/action-electron-builder@master
        with:
          github_token: ${{ secrets.github_token }}
          architectures_mac: "arm64,x64"
          architectures_windows: "ia32,x64"